### ISSUE TITLE
Run recipes/modules/plugins from the command line

### ISSUE THREAD

**Issue by geekscrapy** [securisec/chepy#11]
You may already have this, but I couldn't find a reference. The ability to do something like this in one shot would be amazing. This command _wouldn't_ drop to the chepy cli, but the output would be the shell (bash etc.) terminal.

# chepy rot_13 base64_encode md5 rotate --rotate_by 7 'data_to_be_transformed'

So this would string the modules together, acting on 'data_to_be_transformed'.

This would allow shell scripts to be built against this really, really quickly - or run from the command line and use other commands against it. Only trouble is outputting python objects to the command line (lists, dict etc.)

**Comment by securisec** [comment]
I will consider adding a command line flag to load a recipe, but As you mentioned, passing python objects is not so simple in Cli, and I might not extend the feature request to cover all the possible methods as flags to the Cli. This is where the scripting/library for chepy is handy.
