### ISSUE TITLE
No pcap command: read_pcap

### ISSUE THREAD

**Issue by suricatalfon** [securisec/chepy#17]
**Describe the bug**
No pcap command available.

**To Reproduce**

:~/tmp/analisis/pcap$ chepy p.pcap
>>> read_pcap
ERROR: Could not consume arg: read_pcap

read_pcap is not a valid Chepy method

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Python Version 3.9
 - Chepy Version 3.5

**Comment by securisec** [comment]
Pcap functionalities are provided by plugins. Enable plugins and make sure plugins are installed. 

```sh
❯❯ chepy test.pcapng
❯❯❯ plugins --enable true
INFO:root:Plugins have been enabled. Restart Chepy for effects to take place.
/tmp 7s
❯❯ chepy test.pcapng
❯❯❯ read_pcap
Pcap loaded
❯❯❯
```
