### ISSUE TITLE
Trying to load recipe but get KeyError:

### ISSUE THREAD

**Issue by hmmlaple** [securisec/chepy#22]
**Describe the bug**
A clear and concise description of what the bug is. Do keep in mind that Chepy is attempting to provide functionality that a web app does, which makes it difficult at times to work with certain types of user input. 
I was trying to load a recipe but when i ran the script it gave me error :`  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python310\lib\site-packages\chepy\core.py", line 980, in load_recipe
    function = recipe["function"]
KeyError: 'function`

**To Reproduce**
my script: 
import chepy
from chepy import Chepy
print (
    Chepy("Hello World")
    .load_recipe("C:\\Users\\[REDACTED]\test.recipe")
    .o
)

**Expected behavior**
it to print the encrypted "Hello world"

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version 3.10 (64 bit)
 - Chepy Version (4.0.0)

**Additional context**
I am using a recipe from the cyberchef website so that might be the issue?

**Comment by securisec** [comment]
Yes, cyberchef and chepy recipes are not interchangeable. That is the issue.
