### ISSUE TITLE
How to use chepy to implement the cfb encryption mode of aes?

### ISSUE THREAD

**Issue by shengchenyang** [securisec/chepy#25]
when I use CyberChef to implement the cfb encryption of aes, the corresponding encryption mode is not found in chepy.

An example of CyberChef is shown in the figure：
![image](https://user-images.githubusercontent.com/45198112/198173469-2e0158bd-e67b-45b2-9a53-ecc6766a8ddf.png)

But there is no cfb mode for aes in chepy:
![image](https://user-images.githubusercontent.com/45198112/198174220-b54e2972-680d-448a-8c18-f660811db643.png)

**Comment by securisec** [comment]
Thank you for opening the issue @shengchenyang . I have implemented CFB mode for AES. Do keep in mind that pythons default behavior uses CFB8 mode while CyberChef uses CFB128. Chepy implements CFB128 to stay inline with CyberChef.
