### ISSUE TITLE
to_html_entity  is not working  properly 

### ISSUE THREAD

**Issue by cocoonkid** [securisec/chepy#33]
**Describe the bug**

![image](https://github.com/securisec/chepy/assets/43231640/e8165d20-d9a1-4079-aa28-292fae92ce0a)

**To Reproduce**
Follow  the steps in the screenshot.

**Expected behavior**
Resulst should be  "&#46;&#46;&#47;"

 - OS: Arch
 - 3.12.2
 - chepy 6.6.0

Or maybe  I  am  doing it wrong? I read the  docs but  no dice.

**Comment by securisec** [comment]
@cocoonkid I am not sure what the ask is here. Both the screenshot and your expected results are the same.

**Comment by cocoonkid** [comment]
@securisec  I corrected it. Of course Github was decoding them when out into quotes..
