### ISSUE TITLE
url_safe Does not work

### ISSUE THREAD

**Issue by gachikuku** [securisec/chepy#35]
**Describe the bug**
When using `from_base64(url_safe=True)` an error is thrown.

**To Reproduce**
Simply run the script found here: https://github.com/securisec/chepy/blob/master/docs/examples.md#recipe-5-google-ei-timestamp

**Expected behavior**
I don't expect an error.

**Screenshots**
<img width="724" alt="chepy" src="https://github.com/user-attachments/assets/1fbccd00-ad67-4e95-baa7-83face05b2c5">

**Desktop (please complete the following information):**
 - OS: Macos ARM (Darwin base.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030 arm64)
 - Python 3.12.7
 - chepy 7.2.0

**Additional context**
-

**Comment by securisec** [comment]
The `url_safe` argument was deprecated. The correct convention is `alphabet='url_safe'`. 

https://chepy.readthedocs.io/en/latest/chepy.html?highlight=from_base64#chepy.Chepy.from_base64

```
from chepy import Chepy

c = Chepy('aGVsbG8')

c.from_base64(alphabet='url_safe')

print(c)
# prints hello
```
